# Generated by Django 4.2.5 on 2023-09-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="availability",
            field=models.BooleanField(default=False),
        ),
    ]
